apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-learning-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/amajd58/DEVOPS-learning.git'
    targetRevision: staging
    path: 'k8s'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
