apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-learning-app
  labels:
    app: devops-learning-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: devops-learning-app
  template:
    metadata:
      labels:
        app: devops-learning-app
    spec:
      containers:
        - name: devops-learning-app
          image: 213320332925.dkr.ecr.us-east-1.amazonaws.com/devops-learning-app:eda7a76177d92926a1407ff79f7b830dfe3fd1bf
          imagePullPolicy: Always
          ports:
            - containerPort: 80
